### ISSUE TITLE
Sign in issue when using zello work apk and this issue not found when using pttsdk

### ISSUE THREAD

**Issue by sherihan-abdel-moneim** [zelloptt/zello-android-client-sdk#41] opened 2020-06-18 09:20 UTC

**Comment by adityadalwadi1510** [comment] 2020-10-29 09:13
This is also in our project

**Comment by zello-eugene** [comment] 2020-12-18 02:33
Closing as it's not clear what the problem is. Please feel free to re-open with more details.

**Closed by zello-eugene** 2020-12-18 02:33 UTC
